arm_container:
  image: rust:1.64

task:
  arm_container:
    image: rust:1.64
  env:
    CLONE_URL: "{{ CI_REPOSITORY_URL }}"
    CLONE_SHA: "{{ CI_COMMIT_SHA }}"
  clone_script:
    - git clone "$CLONE_URL"
    - git reset --hard "$CLONE_SHA"
  test_script:
    - cargo test

#  registry_cache:
#    folder: $CARGO_HOME/registry
#    fingerprint_script: cat Cargo.lock
#  target_cache:
#    folder: target
#    fingerprint_script:
#      - rustc --version
#      - cat Cargo.lock
#  build_script: cargo build
#  test_script: cargo test
#  before_cache_script: rm -rf $CARGO_HOME/registry/index

